// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type DroverJobState string

const (
	DroverJobStateAvailable DroverJobState = "available"
	DroverJobStateScheduled DroverJobState = "scheduled"
	DroverJobStateRunning   DroverJobState = "running"
	DroverJobStateRetryable DroverJobState = "retryable"
	DroverJobStateCompleted DroverJobState = "completed"
	DroverJobStateCancelled DroverJobState = "cancelled"
	DroverJobStateDead      DroverJobState = "dead"
)

func (e *DroverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DroverJobState(s)
	case string:
		*e = DroverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for DroverJobState: %T", src)
	}
	return nil
}

type NullDroverJobState struct {
	DroverJobState DroverJobState
	Valid          bool // Valid is true if DroverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDroverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.DroverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DroverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDroverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DroverJobState), nil
}

type DroverInsertBatch struct {
	Ord         int32
	Kind        string
	Queue       string
	Args        []byte
	ScheduledAt *time.Time
	UniqueKey   pgtype.Text
}

type DroverJob struct {
	ID          int64
	Kind        string
	Queue       string
	Args        []byte
	State       DroverJobState
	Attempt     int32
	MaxAttempts int32
	Errors      []byte
	ScheduledAt time.Time
	LeasedUntil *time.Time
	CreatedAt   time.Time
	FinalizedAt *time.Time
	UniqueKey   pgtype.Text
}
