// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const extendLeases = `-- name: ExtendLeases :exec
UPDATE drover_jobs j
SET leased_until = now() + make_interval(secs => $1::float8)
FROM (
    SELECT unnest($2::bigint[]) AS id,
           unnest($3::int[]) AS attempt
) AS held
WHERE j.id = held.id
  AND j.attempt = held.attempt
  AND j.state = 'running'
`

type ExtendLeasesParams struct {
	LeaseSeconds float64
	Ids          []int64
	Attempts     []int32
}

func (q *Queries) ExtendLeases(ctx context.Context, arg ExtendLeasesParams) error {
	_, err := q.db.Exec(ctx, extendLeases, arg.LeaseSeconds, arg.Ids, arg.Attempts)
	return err
}

const fetchAvailable = `-- name: FetchAvailable :many
UPDATE drover_jobs
SET state = 'running',
    attempt = attempt + 1,
    leased_until = now() + make_interval(secs => $1::float8)
WHERE id IN (
    SELECT j.id FROM drover_jobs j
    WHERE j.state IN ('available', 'retryable', 'scheduled')
      AND j.queue = $2
      AND j.scheduled_at <= now()
    -- Ordered by the index's own key, not by id: with queue as an
    -- equality and scheduled_at as a range, the index yields rows in
    -- (scheduled_at, id) order, so ordering by id alone would force
    -- every due row to be read and sorted before LIMIT could take one.
    -- Due-time order is also the more correct claim order — a retry that
    -- came due first should be picked up first.
    ORDER BY j.scheduled_at, j.id
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING id, kind, queue, args, state, attempt, max_attempts, errors, scheduled_at, leased_until, created_at, finalized_at, unique_key
`

type FetchAvailableParams struct {
	LeaseSeconds float64
	Queue        string
	MaxJobs      int32
}

// Lease deadlines are computed here, from the database clock, because
// that is the clock the sweep compares them against. Deriving them on
// the client would make every lease depend on two machines agreeing.
func (q *Queries) FetchAvailable(ctx context.Context, arg FetchAvailableParams) ([]DroverJob, error) {
	rows, err := q.db.Query(ctx, fetchAvailable, arg.LeaseSeconds, arg.Queue, arg.MaxJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DroverJob
	for rows.Next() {
		var i DroverJob
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Queue,
			&i.Args,
			&i.State,
			&i.Attempt,
			&i.MaxAttempts,
			&i.Errors,
			&i.ScheduledAt,
			&i.LeasedUntil,
			&i.CreatedAt,
			&i.FinalizedAt,
			&i.UniqueKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchExpired = `-- name: FetchExpired :many
UPDATE drover_jobs
SET leased_until = now() + make_interval(secs => $1::float8)
WHERE id IN (
    SELECT j.id FROM drover_jobs j
    WHERE j.state = 'running'
      AND j.leased_until <= now()
    -- Oldest lease first, matching the lease index so the batch is taken
    -- without sorting every abandoned row — and recovering the
    -- longest-stranded jobs first.
    ORDER BY j.leased_until, j.id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id, kind, queue, args, state, attempt, max_attempts, errors, scheduled_at, leased_until, created_at, finalized_at, unique_key
`

type FetchExpiredParams struct {
	LeaseSeconds float64
	MaxJobs      int32
}

// FetchExpired re-claims jobs whose worker is presumed dead. attempt is
// deliberately not incremented: the attempt that stranded the row was
// really spent, and counting it twice would halve the effective ceiling
// of every job whose worker ever crashed.
func (q *Queries) FetchExpired(ctx context.Context, arg FetchExpiredParams) ([]DroverJob, error) {
	rows, err := q.db.Query(ctx, fetchExpired, arg.LeaseSeconds, arg.MaxJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DroverJob
	for rows.Next() {
		var i DroverJob
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Queue,
			&i.Args,
			&i.State,
			&i.Attempt,
			&i.MaxAttempts,
			&i.Errors,
			&i.ScheduledAt,
			&i.LeasedUntil,
			&i.CreatedAt,
			&i.FinalizedAt,
			&i.UniqueKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJob = `-- name: GetJob :one
SELECT id, kind, queue, args, state, attempt, max_attempts, errors, scheduled_at, leased_until, created_at, finalized_at, unique_key FROM drover_jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (DroverJob, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i DroverJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Queue,
		&i.Args,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Errors,
		&i.ScheduledAt,
		&i.LeasedUntil,
		&i.CreatedAt,
		&i.FinalizedAt,
		&i.UniqueKey,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO drover_jobs (kind, queue, args, scheduled_at, state, unique_key)
VALUES (
    $1, $2, $3,
    coalesce($4::timestamptz, now()),
    CASE WHEN coalesce($4::timestamptz, now()) > now()
         THEN 'scheduled'::drover_job_state
         ELSE 'available'::drover_job_state
    END,
    $5
)
RETURNING id, kind, queue, args, state, attempt, max_attempts, errors, scheduled_at, leased_until, created_at, finalized_at, unique_key
`

type InsertJobParams struct {
	Kind        string
	Queue       string
	Args        []byte
	ScheduledAt *time.Time
	UniqueKey   pgtype.Text
}

// A null scheduled_at means "now". The state follows from the same
// comparison the fetch predicate makes, evaluated by the database rather
// than the client: a job due later waits in scheduled, one due now is
// available. Deciding this on the client would let a machine running
// fast or slow write a state this database disagrees with, and the state
// column is what an operator is shown.
//
// now() is transaction_timestamp(), so both readings here are the same
// instant and the stored time can never disagree with the state derived
// from it. On the InsertTx path that instant is the caller's transaction
// start, not the insert, so a job enqueued late in a long transaction
// can be recorded scheduled while already due. Nothing is delayed by it:
// the fetch predicate compares scheduled_at against its own now() and
// claims the row on the next poll. clock_timestamp() would fix the label
// and break the guarantee — being volatile, its two occurrences would
// evaluate at different instants and could disagree for real.
func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (DroverJob, error) {
	row := q.db.QueryRow(ctx, insertJob,
		arg.Kind,
		arg.Queue,
		arg.Args,
		arg.ScheduledAt,
		arg.UniqueKey,
	)
	var i DroverJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Queue,
		&i.Args,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Errors,
		&i.ScheduledAt,
		&i.LeasedUntil,
		&i.CreatedAt,
		&i.FinalizedAt,
		&i.UniqueKey,
	)
	return i, err
}

const insertJobsFromStaging = `-- name: InsertJobsFromStaging :many
INSERT INTO drover_jobs (kind, queue, args, scheduled_at, state, unique_key)
SELECT
    kind,
    queue,
    args,
    coalesce(scheduled_at, now()),
    CASE WHEN coalesce(scheduled_at, now()) > now()
         THEN 'scheduled'::drover_job_state
         ELSE 'available'::drover_job_state
    END,
    unique_key
FROM drover_insert_batch
ORDER BY ord
RETURNING id, kind, queue, args, state, attempt, max_attempts, errors, scheduled_at, leased_until, created_at, finalized_at, unique_key
`

// Same CASE as InsertJob: dueness is the database clock's, not the
// client's. Rows are taken from the session-temp staging table in the
// order CopyFrom loaded them.
func (q *Queries) InsertJobsFromStaging(ctx context.Context) ([]DroverJob, error) {
	rows, err := q.db.Query(ctx, insertJobsFromStaging)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DroverJob
	for rows.Next() {
		var i DroverJob
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Queue,
			&i.Args,
			&i.State,
			&i.Attempt,
			&i.MaxAttempts,
			&i.Errors,
			&i.ScheduledAt,
			&i.LeasedUntil,
			&i.CreatedAt,
			&i.FinalizedAt,
			&i.UniqueKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, kind, queue, args, state, attempt, max_attempts, errors, scheduled_at, leased_until, created_at, finalized_at, unique_key FROM drover_jobs
WHERE ($1 = '' OR queue = $1)
  AND ($2::text = '' OR state = $2::drover_job_state)
ORDER BY id DESC
LIMIT $3
`

type ListJobsParams struct {
	Queue   interface{}
	State   string
	MaxJobs int32
}

// Empty queue or state means no filter. Newest id first so a bounded
// listing is stable without a new index, and operators see recent work
// first. Limit is the caller's responsibility to keep positive.
func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]DroverJob, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Queue, arg.State, arg.MaxJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DroverJob
	for rows.Next() {
		var i DroverJob
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Queue,
			&i.Args,
			&i.State,
			&i.Attempt,
			&i.MaxAttempts,
			&i.Errors,
			&i.ScheduledAt,
			&i.LeasedUntil,
			&i.CreatedAt,
			&i.FinalizedAt,
			&i.UniqueKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCancelled = `-- name: MarkCancelled :execrows
UPDATE drover_jobs
SET state = 'cancelled',
    finalized_at = now(),
    leased_until = NULL,
    errors = errors || $1::jsonb
WHERE id = $2 AND attempt = $3 AND state = 'running'
`

type MarkCancelledParams struct {
	Error   []byte
	ID      int64
	Attempt int32
}

func (q *Queries) MarkCancelled(ctx context.Context, arg MarkCancelledParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCancelled, arg.Error, arg.ID, arg.Attempt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markCompleted = `-- name: MarkCompleted :execrows
UPDATE drover_jobs
SET state = 'completed',
    finalized_at = now(),
    leased_until = NULL
WHERE id = $1 AND attempt = $2 AND state = 'running'
`

type MarkCompletedParams struct {
	ID      int64
	Attempt int32
}

// Every finalizer is guarded on the attempt as well as the state. The
// state alone proves some worker holds the row, not that this one does:
// a worker whose heartbeat starved past its lease can find its job
// rescued and re-claimed, and must not then record the outcome of an
// attempt it no longer owns over the one now running.
func (q *Queries) MarkCompleted(ctx context.Context, arg MarkCompletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCompleted, arg.ID, arg.Attempt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDead = `-- name: MarkDead :execrows
UPDATE drover_jobs
SET state = 'dead',
    finalized_at = now(),
    leased_until = NULL,
    errors = errors || $1::jsonb
WHERE id = $2 AND attempt = $3 AND state = 'running'
`

type MarkDeadParams struct {
	Error   []byte
	ID      int64
	Attempt int32
}

func (q *Queries) MarkDead(ctx context.Context, arg MarkDeadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDead, arg.Error, arg.ID, arg.Attempt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRetryable = `-- name: MarkRetryable :execrows
UPDATE drover_jobs
SET state = 'retryable',
    scheduled_at = $1::timestamptz,
    leased_until = NULL,
    errors = errors || $2::jsonb
WHERE id = $3 AND attempt = $4 AND state = 'running'
`

type MarkRetryableParams struct {
	RetryAt time.Time
	Error   []byte
	ID      int64
	Attempt int32
}

func (q *Queries) MarkRetryable(ctx context.Context, arg MarkRetryableParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRetryable,
		arg.RetryAt,
		arg.Error,
		arg.ID,
		arg.Attempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSnoozed = `-- name: MarkSnoozed :execrows
UPDATE drover_jobs
SET state = 'scheduled',
    scheduled_at = $1::timestamptz,
    leased_until = NULL,
    attempt = GREATEST(attempt - 1, 0)
WHERE id = $2 AND attempt = $3 AND state = 'running'
`

type MarkSnoozedParams struct {
	RunAt   time.Time
	ID      int64
	Attempt int32
}

// MarkSnoozed gives back the attempt the claim consumed, floored at zero
// so a deferral can never drive attempt negative or exhaust a job.
func (q *Queries) MarkSnoozed(ctx context.Context, arg MarkSnoozedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSnoozed, arg.RunAt, arg.ID, arg.Attempt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const oldestClaimable = `-- name: OldestClaimable :many
SELECT queue,
       EXTRACT(EPOCH FROM (now() - min(scheduled_at)))::float8 AS age_seconds
FROM drover_jobs
WHERE state IN ('available', 'retryable', 'scheduled')
  AND scheduled_at <= now()
GROUP BY queue
`

type OldestClaimableRow struct {
	Queue      string
	AgeSeconds float64
}

// The predicate is the fetch predicate, deliberately: "oldest job" has to
// mean "oldest job that should already have run", or a job scheduled for
// next week would report a week of lateness the moment it is enqueued and
// every delayed job would look like an outage. Anything that widens what
// FetchAvailable claims has to widen this too, or the age stops measuring
// what the claim round is actually behind on.
//
// The age is subtracted here rather than returned as a timestamp for the
// caller to compare against its own clock: the scheduled time is decided
// by this database's clock, so only this database can say how late it is.
// A client running fast would otherwise publish an age no other client
// agrees with.
func (q *Queries) OldestClaimable(ctx context.Context) ([]OldestClaimableRow, error) {
	rows, err := q.db.Query(ctx, oldestClaimable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OldestClaimableRow
	for rows.Next() {
		var i OldestClaimableRow
		if err := rows.Scan(&i.Queue, &i.AgeSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const operatorCancel = `-- name: OperatorCancel :one
UPDATE drover_jobs
SET state = 'cancelled',
    finalized_at = now(),
    leased_until = NULL
WHERE id = $1
  AND state IN ('available', 'scheduled', 'retryable', 'dead')
RETURNING id, kind, queue, args, state, attempt, max_attempts, errors, scheduled_at, leased_until, created_at, finalized_at, unique_key
`

// Operator cancel is state-conditioned, not lease-fenced: it must not
// invent a fake attempt or stomp a running worker. Zero rows means the
// caller must re-read to distinguish missing from wrong state.
func (q *Queries) OperatorCancel(ctx context.Context, id int64) (DroverJob, error) {
	row := q.db.QueryRow(ctx, operatorCancel, id)
	var i DroverJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Queue,
		&i.Args,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Errors,
		&i.ScheduledAt,
		&i.LeasedUntil,
		&i.CreatedAt,
		&i.FinalizedAt,
		&i.UniqueKey,
	)
	return i, err
}

const queueDepths = `-- name: QueueDepths :many
SELECT queue, state::text AS state, count(*) AS count
FROM drover_jobs
WHERE state IN ('available', 'scheduled', 'retryable', 'running', 'dead')
GROUP BY queue, state
`

type QueueDepthsRow struct {
	Queue string
	State string
	Count int64
}

// Only the states an operator can act on are counted. completed and
// cancelled are deliberately absent: those rows are never removed, so
// counting them would make this query's cost grow with the whole history
// of the queue rather than with its backlog — turning the thing that
// reports load into a source of it. Every state listed here is served by
// a partial index: the three waiting ones by the fetch index, running by
// the lease index, dead by its own.
//
// The cast to text is what keeps the enum out of the driver: without it
// the generated row would carry a generated enum type, and the state
// would have to be translated again on its way to a metric label.
func (q *Queries) QueueDepths(ctx context.Context) ([]QueueDepthsRow, error) {
	rows, err := q.db.Query(ctx, queueDepths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueDepthsRow
	for rows.Next() {
		var i QueueDepthsRow
		if err := rows.Scan(&i.Queue, &i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redriveDead = `-- name: RedriveDead :one
UPDATE drover_jobs
SET state = 'available',
    attempt = 0,
    leased_until = NULL,
    finalized_at = NULL,
    scheduled_at = now()
WHERE id = $1
  AND state = 'dead'
RETURNING id, kind, queue, args, state, attempt, max_attempts, errors, scheduled_at, leased_until, created_at, finalized_at, unique_key
`

// Redrive resets attempt and the lease, keeps error history for triage,
// and uses the database clock for scheduled_at so the job is claimable
// immediately against the same clock the fetch predicate uses.
func (q *Queries) RedriveDead(ctx context.Context, id int64) (DroverJob, error) {
	row := q.db.QueryRow(ctx, redriveDead, id)
	var i DroverJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Queue,
		&i.Args,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Errors,
		&i.ScheduledAt,
		&i.LeasedUntil,
		&i.CreatedAt,
		&i.FinalizedAt,
		&i.UniqueKey,
	)
	return i, err
}
