// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbsqlc

import (
	"context"
	"time"
)

const fetchAvailable = `-- name: FetchAvailable :many
UPDATE drover_jobs
SET state = 'running',
    attempt = attempt + 1,
    leased_until = $1::timestamptz
WHERE id IN (
    SELECT j.id FROM drover_jobs j
    WHERE j.state = 'available'
      AND j.queue = $2
      AND j.scheduled_at <= now()
    ORDER BY j.id
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING id, kind, queue, args, state, attempt, max_attempts, errors, scheduled_at, leased_until, created_at, finalized_at
`

type FetchAvailableParams struct {
	LeasedUntil time.Time
	Queue       string
	MaxJobs     int32
}

func (q *Queries) FetchAvailable(ctx context.Context, arg FetchAvailableParams) ([]DroverJob, error) {
	rows, err := q.db.Query(ctx, fetchAvailable, arg.LeasedUntil, arg.Queue, arg.MaxJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DroverJob
	for rows.Next() {
		var i DroverJob
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Queue,
			&i.Args,
			&i.State,
			&i.Attempt,
			&i.MaxAttempts,
			&i.Errors,
			&i.ScheduledAt,
			&i.LeasedUntil,
			&i.CreatedAt,
			&i.FinalizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJob = `-- name: GetJob :one
SELECT id, kind, queue, args, state, attempt, max_attempts, errors, scheduled_at, leased_until, created_at, finalized_at FROM drover_jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (DroverJob, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i DroverJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Queue,
		&i.Args,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Errors,
		&i.ScheduledAt,
		&i.LeasedUntil,
		&i.CreatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO drover_jobs (kind, queue, args)
VALUES ($1, $2, $3)
RETURNING id, kind, queue, args, state, attempt, max_attempts, errors, scheduled_at, leased_until, created_at, finalized_at
`

type InsertJobParams struct {
	Kind  string
	Queue string
	Args  []byte
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (DroverJob, error) {
	row := q.db.QueryRow(ctx, insertJob, arg.Kind, arg.Queue, arg.Args)
	var i DroverJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Queue,
		&i.Args,
		&i.State,
		&i.Attempt,
		&i.MaxAttempts,
		&i.Errors,
		&i.ScheduledAt,
		&i.LeasedUntil,
		&i.CreatedAt,
		&i.FinalizedAt,
	)
	return i, err
}

const markCompleted = `-- name: MarkCompleted :execrows
UPDATE drover_jobs
SET state = 'completed', finalized_at = now()
WHERE id = $1 AND state = 'running'
`

func (q *Queries) MarkCompleted(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markCompleted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDead = `-- name: MarkDead :execrows
UPDATE drover_jobs
SET state = 'dead',
    finalized_at = now(),
    errors = errors || $2::jsonb
WHERE id = $1 AND state = 'running'
`

type MarkDeadParams struct {
	ID    int64
	Error []byte
}

func (q *Queries) MarkDead(ctx context.Context, arg MarkDeadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDead, arg.ID, arg.Error)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
