// Package pgdriver is the production driver.Driver: PostgreSQL via
// pgx v5, with queries generated by sqlc into internal/dbsqlc
// (generated code is committed; see ADR-0004).
package pgdriver

import (
	"context"
	"errors"
	"fmt"
	"math"
	"slices"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/augusto-dmh/drover/internal/dbsqlc"
	"github.com/augusto-dmh/drover/internal/driver"
	"github.com/augusto-dmh/drover/internal/migrate"
)

// Driver implements driver.Driver on a pgx connection pool.
type Driver struct {
	pool    *pgxpool.Pool
	queries *dbsqlc.Queries
}

// New returns a Driver backed by pool.
func New(pool *pgxpool.Pool) *Driver {
	return &Driver{pool: pool, queries: dbsqlc.New(pool)}
}

// Migrate applies drover's embedded schema migrations.
func (d *Driver) Migrate(ctx context.Context) error {
	return migrate.Migrate(ctx, d.pool)
}

// Insert persists a new available job.
func (d *Driver) Insert(ctx context.Context, params driver.InsertParams) (*driver.JobRow, error) {
	job, err := d.queries.InsertJob(ctx, insertParams(params))
	if err != nil {
		return nil, fmt.Errorf("insert job kind %q: %w", params.Kind, err)
	}
	return rowFromDB(job), nil
}

// InsertTx persists a new available job inside the caller's pgx.Tx, so
// the job exists if and only if that transaction commits.
func (d *Driver) InsertTx(ctx context.Context, tx any, params driver.InsertParams) (*driver.JobRow, error) {
	pgxTx, ok := tx.(pgx.Tx)
	if !ok {
		return nil, fmt.Errorf("pgdriver: tx is %T, want pgx.Tx: %w", tx, driver.ErrTxUnsupported)
	}
	job, err := d.queries.WithTx(pgxTx).InsertJob(ctx, insertParams(params))
	if err != nil {
		return nil, fmt.Errorf("insert job kind %q in tx: %w", params.Kind, err)
	}
	return rowFromDB(job), nil
}

// FetchAvailable claims up to limit due jobs with FOR UPDATE SKIP
// LOCKED, returning them in id order as running with a fresh lease.
func (d *Driver) FetchAvailable(ctx context.Context, queue string, limit int) ([]*driver.JobRow, error) {
	if limit < 0 || limit > math.MaxInt32 {
		return nil, fmt.Errorf("fetch limit %d out of range", limit)
	}
	jobs, err := d.queries.FetchAvailable(ctx, dbsqlc.FetchAvailableParams{
		LeasedUntil: time.Now().Add(driver.DefaultLeaseDuration),
		Queue:       queue,
		MaxJobs:     int32(limit),
	})
	if err != nil {
		return nil, fmt.Errorf("fetch available jobs from queue %q: %w", queue, err)
	}
	return sortedRows(jobs), nil
}

// FetchExpired re-claims up to limit running jobs whose lease has
// passed, taking ownership with a lease that runs to leaseUntil. FOR
// UPDATE SKIP LOCKED is what makes concurrent sweeps disposition each
// row exactly once; attempt is left alone.
func (d *Driver) FetchExpired(ctx context.Context, leaseUntil time.Time, limit int) ([]*driver.JobRow, error) {
	if limit < 0 || limit > math.MaxInt32 {
		return nil, fmt.Errorf("fetch limit %d out of range", limit)
	}
	jobs, err := d.queries.FetchExpired(ctx, dbsqlc.FetchExpiredParams{
		LeasedUntil: leaseUntil,
		MaxJobs:     int32(limit),
	})
	if err != nil {
		return nil, fmt.Errorf("fetch expired jobs: %w", err)
	}
	return sortedRows(jobs), nil
}

// ExtendLeases pushes the lease of every running job in ids out to
// until. Ids that no longer qualify are skipped, not reported: the job
// finalized first, which is a routine race, not a fault.
func (d *Driver) ExtendLeases(ctx context.Context, ids []int64, until time.Time) error {
	if len(ids) == 0 {
		return nil
	}
	if err := d.queries.ExtendLeases(ctx, dbsqlc.ExtendLeasesParams{
		LeasedUntil: until,
		Ids:         ids,
	}); err != nil {
		return fmt.Errorf("extend leases of %d jobs: %w", len(ids), err)
	}
	return nil
}

// MarkCompleted finalizes a running job as completed.
func (d *Driver) MarkCompleted(ctx context.Context, id int64) error {
	affected, err := d.queries.MarkCompleted(ctx, id)
	if err != nil {
		return fmt.Errorf("mark job %d completed: %w", id, err)
	}
	return d.explain(ctx, id, affected)
}

// MarkRetryable returns a running job to the queue at retryAt without
// finalizing it, appending errDetail to its errors array.
func (d *Driver) MarkRetryable(ctx context.Context, id int64, retryAt time.Time, errDetail []byte) error {
	affected, err := d.queries.MarkRetryable(ctx, dbsqlc.MarkRetryableParams{
		ID:      id,
		RetryAt: retryAt,
		Error:   errDetail,
	})
	if err != nil {
		return fmt.Errorf("mark job %d retryable: %w", id, err)
	}
	return d.explain(ctx, id, affected)
}

// MarkDead finalizes a running job as dead, appending errDetail to its
// errors array.
func (d *Driver) MarkDead(ctx context.Context, id int64, errDetail []byte) error {
	affected, err := d.queries.MarkDead(ctx, dbsqlc.MarkDeadParams{ID: id, Error: errDetail})
	if err != nil {
		return fmt.Errorf("mark job %d dead: %w", id, err)
	}
	return d.explain(ctx, id, affected)
}

// MarkCancelled finalizes a running job as cancelled, appending
// errDetail as the reason it will never be retried.
func (d *Driver) MarkCancelled(ctx context.Context, id int64, errDetail []byte) error {
	affected, err := d.queries.MarkCancelled(ctx, dbsqlc.MarkCancelledParams{ID: id, Error: errDetail})
	if err != nil {
		return fmt.Errorf("mark job %d cancelled: %w", id, err)
	}
	return d.explain(ctx, id, affected)
}

// MarkSnoozed defers a running job to runAt, giving back the attempt the
// claim consumed and recording no error.
func (d *Driver) MarkSnoozed(ctx context.Context, id int64, runAt time.Time) error {
	affected, err := d.queries.MarkSnoozed(ctx, dbsqlc.MarkSnoozedParams{ID: id, RunAt: runAt})
	if err != nil {
		return fmt.Errorf("mark job %d snoozed: %w", id, err)
	}
	return d.explain(ctx, id, affected)
}

// explain turns the row count of a guarded transition UPDATE into an
// error: zero rows means the job was not running, and finalizeFailure
// says whether it is missing or merely in the wrong state.
func (d *Driver) explain(ctx context.Context, id int64, affected int64) error {
	if affected == 0 {
		return d.finalizeFailure(ctx, id)
	}
	return nil
}

// finalizeFailure explains why a guarded finalize UPDATE matched no
// row: the job either does not exist or is not running.
func (d *Driver) finalizeFailure(ctx context.Context, id int64) error {
	job, err := d.queries.GetJob(ctx, id)
	if errors.Is(err, pgx.ErrNoRows) {
		return fmt.Errorf("job %d: %w", id, driver.ErrNotFound)
	}
	if err != nil {
		return fmt.Errorf("inspect job %d: %w", id, err)
	}
	return fmt.Errorf("job %d is %s, want running: %w", id, job.State, driver.ErrInvalidTransition)
}

// sortedRows converts claimed jobs to driver rows in id order: UPDATE
// ... RETURNING has no guaranteed order, but the contract is FIFO.
func sortedRows(jobs []dbsqlc.DroverJob) []*driver.JobRow {
	rows := make([]*driver.JobRow, len(jobs))
	for i, job := range jobs {
		rows[i] = rowFromDB(job)
	}
	slices.SortFunc(rows, func(a, b *driver.JobRow) int { return int(a.ID - b.ID) })
	return rows
}

func insertParams(params driver.InsertParams) dbsqlc.InsertJobParams {
	return dbsqlc.InsertJobParams{Kind: params.Kind, Queue: params.Queue, Args: params.Args}
}

func rowFromDB(job dbsqlc.DroverJob) *driver.JobRow {
	return &driver.JobRow{
		ID:          job.ID,
		Kind:        job.Kind,
		Queue:       job.Queue,
		Args:        job.Args,
		State:       string(job.State),
		Attempt:     int(job.Attempt),
		MaxAttempts: int(job.MaxAttempts),
		Errors:      job.Errors,
		ScheduledAt: job.ScheduledAt,
		LeasedUntil: job.LeasedUntil,
		CreatedAt:   job.CreatedAt,
		FinalizedAt: job.FinalizedAt,
	}
}
