// Package pgdriver is the production driver.Driver: PostgreSQL via
// pgx v5, with queries generated by sqlc into internal/dbsqlc
// (generated code is committed; see ADR-0004).
package pgdriver

import (
	"cmp"
	"context"
	"errors"
	"fmt"
	"math"
	"slices"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/augusto-dmh/drover/internal/dbsqlc"
	"github.com/augusto-dmh/drover/internal/driver"
	"github.com/augusto-dmh/drover/internal/migrate"
)

// Driver implements driver.Driver on a pgx connection pool.
type Driver struct {
	pool    *pgxpool.Pool
	queries *dbsqlc.Queries
}

// New returns a Driver backed by pool.
func New(pool *pgxpool.Pool) *Driver {
	return &Driver{pool: pool, queries: dbsqlc.New(pool)}
}

// Migrate applies drover's embedded schema migrations.
func (d *Driver) Migrate(ctx context.Context) error {
	return migrate.Migrate(ctx, d.pool)
}

// Insert persists a new available job.
func (d *Driver) Insert(ctx context.Context, params driver.InsertParams) (*driver.JobRow, error) {
	job, err := d.queries.InsertJob(ctx, insertParams(params))
	if err != nil {
		return nil, fmt.Errorf("insert job kind %q: %w", params.Kind, err)
	}
	return rowFromDB(job), nil
}

// InsertTx persists a new available job inside the caller's pgx.Tx, so
// the job exists if and only if that transaction commits.
func (d *Driver) InsertTx(ctx context.Context, tx any, params driver.InsertParams) (*driver.JobRow, error) {
	pgxTx, ok := tx.(pgx.Tx)
	if !ok {
		return nil, fmt.Errorf("pgdriver: tx is %T, want pgx.Tx: %w", tx, driver.ErrTxUnsupported)
	}
	job, err := d.queries.WithTx(pgxTx).InsertJob(ctx, insertParams(params))
	if err != nil {
		return nil, fmt.Errorf("insert job kind %q in tx: %w", params.Kind, err)
	}
	return rowFromDB(job), nil
}

// Batch-insert stubs satisfy driver.Driver until the Postgres
// implementations land in the next commit.
func (d *Driver) InsertMany(context.Context, []driver.InsertParams) ([]*driver.JobRow, error) {
	panic("pgdriver: InsertMany not implemented")
}

func (d *Driver) InsertManyTx(context.Context, any, []driver.InsertParams) ([]*driver.JobRow, error) {
	panic("pgdriver: InsertManyTx not implemented")
}

// FetchAvailable claims up to limit due jobs with FOR UPDATE SKIP
// LOCKED, returning them in id order as running with a lease lasting
// leaseFor, measured by the database clock.
func (d *Driver) FetchAvailable(ctx context.Context, queue string, leaseFor time.Duration, limit int) ([]*driver.JobRow, error) {
	if limit < 0 || limit > math.MaxInt32 {
		return nil, fmt.Errorf("fetch limit %d out of range", limit)
	}
	jobs, err := d.queries.FetchAvailable(ctx, dbsqlc.FetchAvailableParams{
		LeaseSeconds: leaseFor.Seconds(),
		Queue:        queue,
		MaxJobs:      int32(limit),
	})
	if err != nil {
		return nil, fmt.Errorf("fetch available jobs from queue %q: %w", queue, err)
	}
	return sortedRows(jobs), nil
}

// FetchExpired re-claims up to limit running jobs whose lease has
// passed, taking ownership with a fresh lease lasting leaseFor. FOR
// UPDATE SKIP LOCKED is what makes concurrent sweeps disposition each
// row exactly once; attempt is left alone.
func (d *Driver) FetchExpired(ctx context.Context, leaseFor time.Duration, limit int) ([]*driver.JobRow, error) {
	if limit < 0 || limit > math.MaxInt32 {
		return nil, fmt.Errorf("fetch limit %d out of range", limit)
	}
	jobs, err := d.queries.FetchExpired(ctx, dbsqlc.FetchExpiredParams{
		LeaseSeconds: leaseFor.Seconds(),
		MaxJobs:      int32(limit),
	})
	if err != nil {
		return nil, fmt.Errorf("fetch expired jobs: %w", err)
	}
	return sortedRows(jobs), nil
}

// ExtendLeases pushes each held lease out by another leaseFor. A lease
// whose job finalized or moved to a later attempt is skipped, not
// reported: both race a heartbeat routinely and neither is a fault.
func (d *Driver) ExtendLeases(ctx context.Context, leases []driver.Lease, leaseFor time.Duration) error {
	if len(leases) == 0 {
		return nil
	}
	ids := make([]int64, len(leases))
	attempts := make([]int32, len(leases))
	for i, lease := range leases {
		ids[i] = lease.ID
		attempts[i] = attemptArg(lease.Attempt)
	}
	if err := d.queries.ExtendLeases(ctx, dbsqlc.ExtendLeasesParams{
		LeaseSeconds: leaseFor.Seconds(),
		Ids:          ids,
		Attempts:     attempts,
	}); err != nil {
		return fmt.Errorf("extend leases of %d jobs: %w", len(leases), err)
	}
	return nil
}

// MarkCompleted finalizes a running job as completed.
func (d *Driver) MarkCompleted(ctx context.Context, lease driver.Lease) error {
	affected, err := d.queries.MarkCompleted(ctx, dbsqlc.MarkCompletedParams{
		ID: lease.ID, Attempt: attemptArg(lease.Attempt),
	})
	if err != nil {
		return fmt.Errorf("mark job %d completed: %w", lease.ID, err)
	}
	return d.explain(ctx, lease, affected)
}

// MarkRetryable returns a running job to the queue at retryAt without
// finalizing it, appending errDetail to its errors array.
func (d *Driver) MarkRetryable(ctx context.Context, lease driver.Lease, retryAt time.Time, errDetail []byte) error {
	affected, err := d.queries.MarkRetryable(ctx, dbsqlc.MarkRetryableParams{
		ID:      lease.ID,
		Attempt: attemptArg(lease.Attempt),
		RetryAt: retryAt,
		Error:   errDetail,
	})
	if err != nil {
		return fmt.Errorf("mark job %d retryable: %w", lease.ID, err)
	}
	return d.explain(ctx, lease, affected)
}

// MarkDead finalizes a running job as dead, appending errDetail to its
// errors array.
func (d *Driver) MarkDead(ctx context.Context, lease driver.Lease, errDetail []byte) error {
	affected, err := d.queries.MarkDead(ctx, dbsqlc.MarkDeadParams{
		ID: lease.ID, Attempt: attemptArg(lease.Attempt), Error: errDetail,
	})
	if err != nil {
		return fmt.Errorf("mark job %d dead: %w", lease.ID, err)
	}
	return d.explain(ctx, lease, affected)
}

// MarkCancelled finalizes a running job as cancelled, appending
// errDetail as the reason it will never be retried.
func (d *Driver) MarkCancelled(ctx context.Context, lease driver.Lease, errDetail []byte) error {
	affected, err := d.queries.MarkCancelled(ctx, dbsqlc.MarkCancelledParams{
		ID: lease.ID, Attempt: attemptArg(lease.Attempt), Error: errDetail,
	})
	if err != nil {
		return fmt.Errorf("mark job %d cancelled: %w", lease.ID, err)
	}
	return d.explain(ctx, lease, affected)
}

// MarkSnoozed defers a running job to runAt, giving back the attempt the
// claim consumed and recording no error.
func (d *Driver) MarkSnoozed(ctx context.Context, lease driver.Lease, runAt time.Time) error {
	affected, err := d.queries.MarkSnoozed(ctx, dbsqlc.MarkSnoozedParams{
		ID: lease.ID, Attempt: attemptArg(lease.Attempt), RunAt: runAt,
	})
	if err != nil {
		return fmt.Errorf("mark job %d snoozed: %w", lease.ID, err)
	}
	return d.explain(ctx, lease, affected)
}

// Stats reports the depth of every queue by state, and how long the
// oldest job each queue could hand a worker right now has been waiting.
//
// The age is subtracted by the database, not here: the scheduled time it
// is measured from was decided by that clock, so only that clock can say
// how late a job is. Reading the timestamp back and subtracting the
// caller's own now() would make the number depend on two machines
// agreeing, and a client running fast would publish ages no other client
// in the fleet reports.
func (d *Driver) Stats(ctx context.Context) (*driver.Stats, error) {
	depths, err := d.queries.QueueDepths(ctx)
	if err != nil {
		return nil, fmt.Errorf("count jobs by queue and state: %w", err)
	}
	oldest, err := d.queries.OldestClaimable(ctx)
	if err != nil {
		return nil, fmt.Errorf("age the oldest claimable job of each queue: %w", err)
	}

	stats := &driver.Stats{}
	for _, row := range depths {
		stats.Depths = append(stats.Depths, driver.QueueDepth{
			Queue: row.Queue, State: row.State, Count: row.Count,
		})
	}
	for _, row := range oldest {
		stats.Oldest = append(stats.Oldest, driver.QueueAge{
			Queue: row.Queue, AgeSeconds: row.AgeSeconds,
		})
	}
	// GROUP BY has no guaranteed output order and the contract has one,
	// for the same reason sortedRows exists: a reading is compared against
	// another driver's reading of the same jobs, and that only means
	// something if neither leaves the order to the planner.
	slices.SortFunc(stats.Depths, func(a, b driver.QueueDepth) int {
		if c := cmp.Compare(a.Queue, b.Queue); c != 0 {
			return c
		}
		return cmp.Compare(a.State, b.State)
	})
	slices.SortFunc(stats.Oldest, func(a, b driver.QueueAge) int {
		return cmp.Compare(a.Queue, b.Queue)
	})
	return stats, nil
}

// ListJobs returns jobs matching optional queue and state filters,
// newest id first, capped at p.Limit. A non-positive Limit is refused.
func (d *Driver) ListJobs(ctx context.Context, p driver.ListJobsParams) ([]*driver.JobRow, error) {
	if p.Limit <= 0 {
		return nil, fmt.Errorf("list limit must be positive, got %d", p.Limit)
	}
	if p.Limit > math.MaxInt32 {
		return nil, fmt.Errorf("list limit %d out of range", p.Limit)
	}
	jobs, err := d.queries.ListJobs(ctx, dbsqlc.ListJobsParams{
		Queue:   p.Queue,
		State:   p.State,
		MaxJobs: int32(p.Limit),
	})
	if err != nil {
		return nil, fmt.Errorf("list jobs: %w", err)
	}
	rows := make([]*driver.JobRow, len(jobs))
	for i, job := range jobs {
		rows[i] = rowFromDB(job)
	}
	return rows, nil
}

// GetJob returns the current row for id, or ErrNotFound.
func (d *Driver) GetJob(ctx context.Context, id int64) (*driver.JobRow, error) {
	job, err := d.queries.GetJob(ctx, id)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, fmt.Errorf("job %d: %w", id, driver.ErrNotFound)
	}
	if err != nil {
		return nil, fmt.Errorf("get job %d: %w", id, err)
	}
	return rowFromDB(job), nil
}

// OperatorCancel moves a waiting or dead job to cancelled. A zero-row
// update is re-read so missing ids and wrong states stay distinguishable.
// When the re-read shows an allowed state (TOCTOU with a concurrent
// transition into eligibility), the UPDATE is retried once.
func (d *Driver) OperatorCancel(ctx context.Context, id int64) (*driver.JobRow, error) {
	return d.operatorCancel(ctx, id, true)
}

func (d *Driver) operatorCancel(ctx context.Context, id int64, allowRetry bool) (*driver.JobRow, error) {
	job, err := d.queries.OperatorCancel(ctx, id)
	if errors.Is(err, pgx.ErrNoRows) {
		return d.afterOperatorMiss(ctx, id, "cancellable", allowRetry, func() (*driver.JobRow, error) {
			return d.operatorCancel(ctx, id, false)
		})
	}
	if err != nil {
		return nil, fmt.Errorf("cancel job %d: %w", id, err)
	}
	return rowFromDB(job), nil
}

// RedriveDead returns a dead job to available with attempt reset. A
// zero-row update is re-read so missing ids and wrong states stay
// distinguishable. When the re-read shows dead (TOCTOU into eligibility),
// the UPDATE is retried once.
func (d *Driver) RedriveDead(ctx context.Context, id int64) (*driver.JobRow, error) {
	return d.redriveDead(ctx, id, true)
}

func (d *Driver) redriveDead(ctx context.Context, id int64, allowRetry bool) (*driver.JobRow, error) {
	job, err := d.queries.RedriveDead(ctx, id)
	if errors.Is(err, pgx.ErrNoRows) {
		return d.afterOperatorMiss(ctx, id, "dead", allowRetry, func() (*driver.JobRow, error) {
			return d.redriveDead(ctx, id, false)
		})
	}
	if err != nil {
		return nil, fmt.Errorf("redrive job %d: %w", id, err)
	}
	return rowFromDB(job), nil
}

// operatorEligible reports whether the current state matches what an
// operator UPDATE for want would accept.
func operatorEligible(state dbsqlc.DroverJobState, want string) bool {
	switch want {
	case "cancellable":
		switch state {
		case dbsqlc.DroverJobStateAvailable,
			dbsqlc.DroverJobStateScheduled,
			dbsqlc.DroverJobStateRetryable,
			dbsqlc.DroverJobStateDead:
			return true
		}
	case "dead":
		return state == dbsqlc.DroverJobStateDead
	}
	return false
}

// afterOperatorMiss explains a zero-row operator UPDATE. When the
// re-read shows an allowed state and allowRetry is set, retry runs once
// instead of returning ErrInvalidTransition.
func (d *Driver) afterOperatorMiss(
	ctx context.Context,
	id int64,
	want string,
	allowRetry bool,
	retry func() (*driver.JobRow, error),
) (*driver.JobRow, error) {
	job, err := d.queries.GetJob(ctx, id)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, fmt.Errorf("job %d: %w", id, driver.ErrNotFound)
	}
	if err != nil {
		return nil, fmt.Errorf("inspect job %d: %w", id, err)
	}
	if allowRetry && operatorEligible(job.State, want) {
		return retry()
	}
	return nil, fmt.Errorf("job %d is %s, want %s: %w", id, job.State, want, driver.ErrInvalidTransition)
}

// explain turns the row count of a guarded transition UPDATE into an
// error: zero rows means the lease did not match, and finalizeFailure
// says why.
func (d *Driver) explain(ctx context.Context, lease driver.Lease, affected int64) error {
	if affected == 0 {
		return d.finalizeFailure(ctx, lease)
	}
	return nil
}

// finalizeFailure explains why a guarded transition matched no row: the
// job is missing, it has moved on to an attempt this caller does not
// hold, or it is simply not running.
func (d *Driver) finalizeFailure(ctx context.Context, lease driver.Lease) error {
	job, err := d.queries.GetJob(ctx, lease.ID)
	if errors.Is(err, pgx.ErrNoRows) {
		return fmt.Errorf("job %d: %w", lease.ID, driver.ErrNotFound)
	}
	if err != nil {
		return fmt.Errorf("inspect job %d: %w", lease.ID, err)
	}
	// State first: a job that is not running was never this caller's to
	// finish, whoever holds it. Only once it *is* running does the
	// attempt distinguish "mine" from "someone else's".
	if job.State != dbsqlc.DroverJobStateRunning {
		return fmt.Errorf("job %d is %s, want running: %w", lease.ID, job.State, driver.ErrInvalidTransition)
	}
	return fmt.Errorf("job %d is on attempt %d, held attempt %d: %w",
		lease.ID, job.Attempt, lease.Attempt, driver.ErrLeaseLost)
}

// sortedRows converts claimed jobs to driver rows in id order: UPDATE
// ... RETURNING has no guaranteed order, but the contract is FIFO.
func sortedRows(jobs []dbsqlc.DroverJob) []*driver.JobRow {
	rows := make([]*driver.JobRow, len(jobs))
	for i, job := range jobs {
		rows[i] = rowFromDB(job)
	}
	slices.SortFunc(rows, func(a, b *driver.JobRow) int { return int(a.ID - b.ID) })
	return rows
}

// attemptArg narrows an attempt number for the wire. Attempt lives in an
// int32 column, so a value read back from the database always fits;
// clamping rather than converting blindly keeps a corrupted in-memory
// value from wrapping into some other attempt number and matching a row
// this caller does not hold.
func attemptArg(attempt int) int32 {
	switch {
	case attempt < 0:
		return 0
	case attempt > math.MaxInt32:
		return math.MaxInt32
	default:
		return int32(attempt)
	}
}

func insertParams(params driver.InsertParams) dbsqlc.InsertJobParams {
	out := dbsqlc.InsertJobParams{Kind: params.Kind, Queue: params.Queue, Args: params.Args}
	// Left null for the zero time so the statement substitutes now() and
	// the database decides both the scheduled time and the state.
	if !params.ScheduledAt.IsZero() {
		at := params.ScheduledAt
		out.ScheduledAt = &at
	}
	return out
}

func rowFromDB(job dbsqlc.DroverJob) *driver.JobRow {
	return &driver.JobRow{
		ID:          job.ID,
		Kind:        job.Kind,
		Queue:       job.Queue,
		Args:        job.Args,
		State:       string(job.State),
		Attempt:     int(job.Attempt),
		MaxAttempts: int(job.MaxAttempts),
		Errors:      job.Errors,
		ScheduledAt: job.ScheduledAt,
		LeasedUntil: job.LeasedUntil,
		CreatedAt:   job.CreatedAt,
		FinalizedAt: job.FinalizedAt,
	}
}
